export const BUILDING_CATEGORIES = ['建物', '家具', '農業', '道具'];

export const BUILDINGS = {
  wood_wall: {
    id: 'wood_wall', name: '木の壁', category: '建物',
    cost: { wood: 2 },
    w: 1, h: 1.5, d: 0.25,
    color: 0x8B4513, solid: true,
    description: '丈夫な木製の壁',
  },
  stone_wall: {
    id: 'stone_wall', name: '石の壁', category: '建物',
    cost: { stone: 3 },
    w: 1, h: 1.5, d: 0.25,
    color: 0x808080, solid: true,
    description: '頑丈な石造りの壁',
  },
  wood_floor: {
    id: 'wood_floor', name: '木の床', category: '建物',
    cost: { wood: 1 },
    w: 1, h: 0.1, d: 1,
    color: 0xA0522D, solid: false,
    description: '温かみのある木の床',
  },
  stone_floor: {
    id: 'stone_floor', name: '石畳（床）', category: '建物',
    cost: { stone: 2 },
    w: 1, h: 0.08, d: 1,
    color: 0x969696, solid: false,
    description: '頑丈な石畳',
  },
  roof: {
    id: 'roof', name: '三角屋根', category: '建物',
    cost: { wood: 3 },
    w: 1, h: 0.8, d: 1,
    color: 0x8B3A3A, solid: false,
    isRoof: true,
    description: '雨をしのぐ三角屋根',
  },
  flat_roof: {
    id: 'flat_roof', name: '平らな屋根板', category: '建物',
    cost: { wood: 2 },
    w: 1.02, h: 0.12, d: 1.02,
    color: 0x2244aa, solid: false,
    description: '平らな屋根板（重ねて高い建物の屋根に）',
  },
  door: {
    id: 'door', name: 'ドア', category: '建物',
    cost: { wood: 2 },
    w: 0.2, h: 1.4, d: 0.8,
    color: 0x6B3A2A, solid: false,
    description: '出入り口のドア',
  },
  campfire: {
    id: 'campfire', name: '焚き火', category: '家具',
    cost: { stone: 2 },
    w: 0.6, h: 0.5, d: 0.6,
    color: 0xFF6600, solid: false,
    emissive: 0xFF3300, emissiveIntensity: 0.8,
    light: { color: 0xFF8800, intensity: 2, distance: 6 },
    description: '暖を取るための焚き火',
  },
  lantern: {
    id: 'lantern', name: 'ランタン', category: '家具',
    cost: { iron: 1, cloth: 1 },
    w: 0.3, h: 0.8, d: 0.3,
    color: 0xFFAA00, solid: false,
    emissive: 0xFFCC00, emissiveIntensity: 1.0,
    light: { color: 0xFFAA44, intensity: 1.5, distance: 5 },
    description: '明かりを灯すランタン',
  },
  table: {
    id: 'table', name: 'テーブル', category: '家具',
    cost: { wood: 3 },
    w: 1, h: 0.6, d: 0.6,
    color: 0x9B6B3A, solid: false,
    description: '食事や作業に使うテーブル',
  },
  bed: {
    id: 'bed', name: 'ベッド', category: '家具',
    cost: { wood: 4, cloth: 1 },
    w: 1, h: 0.5, d: 2,
    color: 0x6688AA, solid: false,
    description: '体を休めるベッド',
  },
  chest: {
    id: 'chest', name: 'チェスト', category: '家具',
    cost: { wood: 5 },
    w: 0.8, h: 0.6, d: 0.6,
    color: 0x8B5A2B, solid: false,
    isChest: true,
    description: 'アイテムを保管するチェスト（20スロット）',
  },
  well: {
    id: 'well', name: '井戸', category: '農業',
    cost: { stone: 5 },
    w: 1, h: 1.2, d: 1,
    color: 0x707070, solid: true,
    isWell: true,
    description: '水を汲む井戸',
  },
  farm_plot: {
    id: 'farm_plot', name: '畑マーカー', category: '農業',
    cost: {},
    w: 1, h: 0.01, d: 1,
    color: 0x3a2010, solid: false,
    description: '耕した畑',
    hidden: true,
  },

  // ── 道具 ────────────────────────────────────────────────────────────────
  axe: {
    id: 'axe', name: '斧', category: '道具',
    cost: { wood: 5, stone: 2 },
    isTool: true,
    description: '木を切り倒す斧。SPACEで使用。',
  },
  pickaxe: {
    id: 'pickaxe', name: 'つるはし', category: '道具',
    cost: { wood: 3, stone: 5 },
    isTool: true,
    description: '岩を砕くつるはし。SPACEで使用。',
  },
};
